### ISSUE TITLE
but it works on my machine!

### ISSUE THREAD

**Issue by EGA-SUPREMO** [EGA-SUPREMO/fv#8]
CONO DE SU MAQUINA
java.io.IOException: Problem reading font data.
        at java.desktop/java.awt.Font.createFont0(Font.java:1205)
        at java.desktop/java.awt.Font.createFont(Font.java:1076)
        at qef.ilj.YargxilAzhj.yargxFontn(YargxilAzhj.java:290)
        at qef.Konstantj.<clinit>(Konstantj.java:137)
        at qef.Qefperant.main(Qefperant.java:44)
CONO DE SU MAQUINA
java.io.IOException: Problem reading font data.
        at java.desktop/java.awt.Font.createFont0(Font.java:1205)
        at java.desktop/java.awt.Font.createFont(Font.java:1076)
        at qef.ilj.YargxilAzhj.yargxFontn(YargxilAzhj.java:290)
        at qef.Konstantj.<clinit>(Konstantj.java:138)
        at qef.Qefperant.main(Qefperant.java:44)
CONO DE SU MAQUINA
java.io.IOException: Problem reading font data.
        at java.desktop/java.awt.Font.createFont0(Font.java:1205)
        at java.desktop/java.awt.Font.createFont(Font.java:1076)
        at qef.ilj.YargxilAzhj.yargxFontn(YargxilAzhj.java:290)
        at qef.Konstantj.<clinit>(Konstantj.java:139)
        at qef.Qefperant.main(Qefperant.java:44)
/images/icons/blue_button_1.png
input == null!
Exception in thread "main" java.lang.ExceptionInInitializerError
        at qef.Qefperant.main(Qefperant.java:44)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Throwable.getLocalizedMessage()" because the return value of "java.lang.Exception.getCause()" is null
        at qef.ilj.YargxilAzhj.yargxBildn(YargxilAzhj.java:46)
        at qef.Konstantj.<clinit>(Konstantj.java:164)
        ... 1 more

**Comment by EGA-SUPREMO** [comment]
it shows that error when using java 19, but works perfectly with java 8
